/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package kl.hsm.server.svc.base;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-01-24")
public class EdDsaKeyPair implements org.apache.thrift.TBase<EdDsaKeyPair, EdDsaKeyPair._Fields>, java.io.Serializable, Cloneable, Comparable<EdDsaKeyPair> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EdDsaKeyPair");

  private static final org.apache.thrift.protocol.TField PUB_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("pubKey", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField PRI_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("priKey", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new EdDsaKeyPairStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new EdDsaKeyPairTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable EdDsaRefPublicKey pubKey; // required
  public @org.apache.thrift.annotation.Nullable EdDsaRefPrivateKey priKey; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PUB_KEY((short)1, "pubKey"),
    PRI_KEY((short)2, "priKey");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PUB_KEY
          return PUB_KEY;
        case 2: // PRI_KEY
          return PRI_KEY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PUB_KEY, new org.apache.thrift.meta_data.FieldMetaData("pubKey", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, EdDsaRefPublicKey.class)));
    tmpMap.put(_Fields.PRI_KEY, new org.apache.thrift.meta_data.FieldMetaData("priKey", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, EdDsaRefPrivateKey.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EdDsaKeyPair.class, metaDataMap);
  }

  public EdDsaKeyPair() {
  }

  public EdDsaKeyPair(
    EdDsaRefPublicKey pubKey,
    EdDsaRefPrivateKey priKey)
  {
    this();
    this.pubKey = pubKey;
    this.priKey = priKey;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EdDsaKeyPair(EdDsaKeyPair other) {
    if (other.isSetPubKey()) {
      this.pubKey = new EdDsaRefPublicKey(other.pubKey);
    }
    if (other.isSetPriKey()) {
      this.priKey = new EdDsaRefPrivateKey(other.priKey);
    }
  }

  @Override
  public EdDsaKeyPair deepCopy() {
    return new EdDsaKeyPair(this);
  }

  @Override
  public void clear() {
    this.pubKey = null;
    this.priKey = null;
  }

  @org.apache.thrift.annotation.Nullable
  public EdDsaRefPublicKey getPubKey() {
    return this.pubKey;
  }

  public EdDsaKeyPair setPubKey(@org.apache.thrift.annotation.Nullable EdDsaRefPublicKey pubKey) {
    this.pubKey = pubKey;
    return this;
  }

  public void unsetPubKey() {
    this.pubKey = null;
  }

  /** Returns true if field pubKey is set (has been assigned a value) and false otherwise */
  public boolean isSetPubKey() {
    return this.pubKey != null;
  }

  public void setPubKeyIsSet(boolean value) {
    if (!value) {
      this.pubKey = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public EdDsaRefPrivateKey getPriKey() {
    return this.priKey;
  }

  public EdDsaKeyPair setPriKey(@org.apache.thrift.annotation.Nullable EdDsaRefPrivateKey priKey) {
    this.priKey = priKey;
    return this;
  }

  public void unsetPriKey() {
    this.priKey = null;
  }

  /** Returns true if field priKey is set (has been assigned a value) and false otherwise */
  public boolean isSetPriKey() {
    return this.priKey != null;
  }

  public void setPriKeyIsSet(boolean value) {
    if (!value) {
      this.priKey = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PUB_KEY:
      if (value == null) {
        unsetPubKey();
      } else {
        setPubKey((EdDsaRefPublicKey)value);
      }
      break;

    case PRI_KEY:
      if (value == null) {
        unsetPriKey();
      } else {
        setPriKey((EdDsaRefPrivateKey)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PUB_KEY:
      return getPubKey();

    case PRI_KEY:
      return getPriKey();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PUB_KEY:
      return isSetPubKey();
    case PRI_KEY:
      return isSetPriKey();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof EdDsaKeyPair)
      return this.equals((EdDsaKeyPair)that);
    return false;
  }

  public boolean equals(EdDsaKeyPair that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_pubKey = true && this.isSetPubKey();
    boolean that_present_pubKey = true && that.isSetPubKey();
    if (this_present_pubKey || that_present_pubKey) {
      if (!(this_present_pubKey && that_present_pubKey))
        return false;
      if (!this.pubKey.equals(that.pubKey))
        return false;
    }

    boolean this_present_priKey = true && this.isSetPriKey();
    boolean that_present_priKey = true && that.isSetPriKey();
    if (this_present_priKey || that_present_priKey) {
      if (!(this_present_priKey && that_present_priKey))
        return false;
      if (!this.priKey.equals(that.priKey))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPubKey()) ? 131071 : 524287);
    if (isSetPubKey())
      hashCode = hashCode * 8191 + pubKey.hashCode();

    hashCode = hashCode * 8191 + ((isSetPriKey()) ? 131071 : 524287);
    if (isSetPriKey())
      hashCode = hashCode * 8191 + priKey.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(EdDsaKeyPair other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetPubKey(), other.isSetPubKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPubKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pubKey, other.pubKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPriKey(), other.isSetPriKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPriKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.priKey, other.priKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("EdDsaKeyPair(");
    boolean first = true;

    sb.append("pubKey:");
    if (this.pubKey == null) {
      sb.append("null");
    } else {
      sb.append(this.pubKey);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("priKey:");
    if (this.priKey == null) {
      sb.append("null");
    } else {
      sb.append(this.priKey);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (pubKey != null) {
      pubKey.validate();
    }
    if (priKey != null) {
      priKey.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EdDsaKeyPairStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public EdDsaKeyPairStandardScheme getScheme() {
      return new EdDsaKeyPairStandardScheme();
    }
  }

  private static class EdDsaKeyPairStandardScheme extends org.apache.thrift.scheme.StandardScheme<EdDsaKeyPair> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, EdDsaKeyPair struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PUB_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.pubKey = new EdDsaRefPublicKey();
              struct.pubKey.read(iprot);
              struct.setPubKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PRI_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.priKey = new EdDsaRefPrivateKey();
              struct.priKey.read(iprot);
              struct.setPriKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, EdDsaKeyPair struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.pubKey != null) {
        oprot.writeFieldBegin(PUB_KEY_FIELD_DESC);
        struct.pubKey.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.priKey != null) {
        oprot.writeFieldBegin(PRI_KEY_FIELD_DESC);
        struct.priKey.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EdDsaKeyPairTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public EdDsaKeyPairTupleScheme getScheme() {
      return new EdDsaKeyPairTupleScheme();
    }
  }

  private static class EdDsaKeyPairTupleScheme extends org.apache.thrift.scheme.TupleScheme<EdDsaKeyPair> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EdDsaKeyPair struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPubKey()) {
        optionals.set(0);
      }
      if (struct.isSetPriKey()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPubKey()) {
        struct.pubKey.write(oprot);
      }
      if (struct.isSetPriKey()) {
        struct.priKey.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EdDsaKeyPair struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.pubKey = new EdDsaRefPublicKey();
        struct.pubKey.read(iprot);
        struct.setPubKeyIsSet(true);
      }
      if (incoming.get(1)) {
        struct.priKey = new EdDsaRefPrivateKey();
        struct.priKey.read(iprot);
        struct.setPriKeyIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

