/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package kl.hsm.server.svc.base;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-01-24")
public class KeyPairWithKek implements org.apache.thrift.TBase<KeyPairWithKek, KeyPairWithKek._Fields>, java.io.Serializable, Cloneable, Comparable<KeyPairWithKek> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("KeyPairWithKek");

  private static final org.apache.thrift.protocol.TField HANDLER_FIELD_DESC = new org.apache.thrift.protocol.TField("handler", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField PUB_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("pubKey", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PRI_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("priKey", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField PUC_TAG_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("pucTagData", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new KeyPairWithKekStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new KeyPairWithKekTupleSchemeFactory();

  public long handler; // required
  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer pubKey; // required
  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer priKey; // required
  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer pucTagData; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    HANDLER((short)1, "handler"),
    PUB_KEY((short)2, "pubKey"),
    PRI_KEY((short)3, "priKey"),
    PUC_TAG_DATA((short)4, "pucTagData");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // HANDLER
          return HANDLER;
        case 2: // PUB_KEY
          return PUB_KEY;
        case 3: // PRI_KEY
          return PRI_KEY;
        case 4: // PUC_TAG_DATA
          return PUC_TAG_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __HANDLER_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.HANDLER, new org.apache.thrift.meta_data.FieldMetaData("handler", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.PUB_KEY, new org.apache.thrift.meta_data.FieldMetaData("pubKey", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.PRI_KEY, new org.apache.thrift.meta_data.FieldMetaData("priKey", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.PUC_TAG_DATA, new org.apache.thrift.meta_data.FieldMetaData("pucTagData", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(KeyPairWithKek.class, metaDataMap);
  }

  public KeyPairWithKek() {
  }

  public KeyPairWithKek(
    long handler,
    java.nio.ByteBuffer pubKey,
    java.nio.ByteBuffer priKey,
    java.nio.ByteBuffer pucTagData)
  {
    this();
    this.handler = handler;
    setHandlerIsSet(true);
    this.pubKey = org.apache.thrift.TBaseHelper.copyBinary(pubKey);
    this.priKey = org.apache.thrift.TBaseHelper.copyBinary(priKey);
    this.pucTagData = org.apache.thrift.TBaseHelper.copyBinary(pucTagData);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public KeyPairWithKek(KeyPairWithKek other) {
    __isset_bitfield = other.__isset_bitfield;
    this.handler = other.handler;
    if (other.isSetPubKey()) {
      this.pubKey = org.apache.thrift.TBaseHelper.copyBinary(other.pubKey);
    }
    if (other.isSetPriKey()) {
      this.priKey = org.apache.thrift.TBaseHelper.copyBinary(other.priKey);
    }
    if (other.isSetPucTagData()) {
      this.pucTagData = org.apache.thrift.TBaseHelper.copyBinary(other.pucTagData);
    }
  }

  @Override
  public KeyPairWithKek deepCopy() {
    return new KeyPairWithKek(this);
  }

  @Override
  public void clear() {
    setHandlerIsSet(false);
    this.handler = 0;
    this.pubKey = null;
    this.priKey = null;
    this.pucTagData = null;
  }

  public long getHandler() {
    return this.handler;
  }

  public KeyPairWithKek setHandler(long handler) {
    this.handler = handler;
    setHandlerIsSet(true);
    return this;
  }

  public void unsetHandler() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __HANDLER_ISSET_ID);
  }

  /** Returns true if field handler is set (has been assigned a value) and false otherwise */
  public boolean isSetHandler() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __HANDLER_ISSET_ID);
  }

  public void setHandlerIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __HANDLER_ISSET_ID, value);
  }

  public byte[] getPubKey() {
    setPubKey(org.apache.thrift.TBaseHelper.rightSize(pubKey));
    return pubKey == null ? null : pubKey.array();
  }

  public java.nio.ByteBuffer bufferForPubKey() {
    return org.apache.thrift.TBaseHelper.copyBinary(pubKey);
  }

  public KeyPairWithKek setPubKey(byte[] pubKey) {
    this.pubKey = pubKey == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(pubKey.clone());
    return this;
  }

  public KeyPairWithKek setPubKey(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer pubKey) {
    this.pubKey = org.apache.thrift.TBaseHelper.copyBinary(pubKey);
    return this;
  }

  public void unsetPubKey() {
    this.pubKey = null;
  }

  /** Returns true if field pubKey is set (has been assigned a value) and false otherwise */
  public boolean isSetPubKey() {
    return this.pubKey != null;
  }

  public void setPubKeyIsSet(boolean value) {
    if (!value) {
      this.pubKey = null;
    }
  }

  public byte[] getPriKey() {
    setPriKey(org.apache.thrift.TBaseHelper.rightSize(priKey));
    return priKey == null ? null : priKey.array();
  }

  public java.nio.ByteBuffer bufferForPriKey() {
    return org.apache.thrift.TBaseHelper.copyBinary(priKey);
  }

  public KeyPairWithKek setPriKey(byte[] priKey) {
    this.priKey = priKey == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(priKey.clone());
    return this;
  }

  public KeyPairWithKek setPriKey(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer priKey) {
    this.priKey = org.apache.thrift.TBaseHelper.copyBinary(priKey);
    return this;
  }

  public void unsetPriKey() {
    this.priKey = null;
  }

  /** Returns true if field priKey is set (has been assigned a value) and false otherwise */
  public boolean isSetPriKey() {
    return this.priKey != null;
  }

  public void setPriKeyIsSet(boolean value) {
    if (!value) {
      this.priKey = null;
    }
  }

  public byte[] getPucTagData() {
    setPucTagData(org.apache.thrift.TBaseHelper.rightSize(pucTagData));
    return pucTagData == null ? null : pucTagData.array();
  }

  public java.nio.ByteBuffer bufferForPucTagData() {
    return org.apache.thrift.TBaseHelper.copyBinary(pucTagData);
  }

  public KeyPairWithKek setPucTagData(byte[] pucTagData) {
    this.pucTagData = pucTagData == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(pucTagData.clone());
    return this;
  }

  public KeyPairWithKek setPucTagData(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer pucTagData) {
    this.pucTagData = org.apache.thrift.TBaseHelper.copyBinary(pucTagData);
    return this;
  }

  public void unsetPucTagData() {
    this.pucTagData = null;
  }

  /** Returns true if field pucTagData is set (has been assigned a value) and false otherwise */
  public boolean isSetPucTagData() {
    return this.pucTagData != null;
  }

  public void setPucTagDataIsSet(boolean value) {
    if (!value) {
      this.pucTagData = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case HANDLER:
      if (value == null) {
        unsetHandler();
      } else {
        setHandler((java.lang.Long)value);
      }
      break;

    case PUB_KEY:
      if (value == null) {
        unsetPubKey();
      } else {
        if (value instanceof byte[]) {
          setPubKey((byte[])value);
        } else {
          setPubKey((java.nio.ByteBuffer)value);
        }
      }
      break;

    case PRI_KEY:
      if (value == null) {
        unsetPriKey();
      } else {
        if (value instanceof byte[]) {
          setPriKey((byte[])value);
        } else {
          setPriKey((java.nio.ByteBuffer)value);
        }
      }
      break;

    case PUC_TAG_DATA:
      if (value == null) {
        unsetPucTagData();
      } else {
        if (value instanceof byte[]) {
          setPucTagData((byte[])value);
        } else {
          setPucTagData((java.nio.ByteBuffer)value);
        }
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case HANDLER:
      return getHandler();

    case PUB_KEY:
      return getPubKey();

    case PRI_KEY:
      return getPriKey();

    case PUC_TAG_DATA:
      return getPucTagData();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case HANDLER:
      return isSetHandler();
    case PUB_KEY:
      return isSetPubKey();
    case PRI_KEY:
      return isSetPriKey();
    case PUC_TAG_DATA:
      return isSetPucTagData();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof KeyPairWithKek)
      return this.equals((KeyPairWithKek)that);
    return false;
  }

  public boolean equals(KeyPairWithKek that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_handler = true;
    boolean that_present_handler = true;
    if (this_present_handler || that_present_handler) {
      if (!(this_present_handler && that_present_handler))
        return false;
      if (this.handler != that.handler)
        return false;
    }

    boolean this_present_pubKey = true && this.isSetPubKey();
    boolean that_present_pubKey = true && that.isSetPubKey();
    if (this_present_pubKey || that_present_pubKey) {
      if (!(this_present_pubKey && that_present_pubKey))
        return false;
      if (!this.pubKey.equals(that.pubKey))
        return false;
    }

    boolean this_present_priKey = true && this.isSetPriKey();
    boolean that_present_priKey = true && that.isSetPriKey();
    if (this_present_priKey || that_present_priKey) {
      if (!(this_present_priKey && that_present_priKey))
        return false;
      if (!this.priKey.equals(that.priKey))
        return false;
    }

    boolean this_present_pucTagData = true && this.isSetPucTagData();
    boolean that_present_pucTagData = true && that.isSetPucTagData();
    if (this_present_pucTagData || that_present_pucTagData) {
      if (!(this_present_pucTagData && that_present_pucTagData))
        return false;
      if (!this.pucTagData.equals(that.pucTagData))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(handler);

    hashCode = hashCode * 8191 + ((isSetPubKey()) ? 131071 : 524287);
    if (isSetPubKey())
      hashCode = hashCode * 8191 + pubKey.hashCode();

    hashCode = hashCode * 8191 + ((isSetPriKey()) ? 131071 : 524287);
    if (isSetPriKey())
      hashCode = hashCode * 8191 + priKey.hashCode();

    hashCode = hashCode * 8191 + ((isSetPucTagData()) ? 131071 : 524287);
    if (isSetPucTagData())
      hashCode = hashCode * 8191 + pucTagData.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(KeyPairWithKek other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetHandler(), other.isSetHandler());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHandler()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.handler, other.handler);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPubKey(), other.isSetPubKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPubKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pubKey, other.pubKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPriKey(), other.isSetPriKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPriKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.priKey, other.priKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPucTagData(), other.isSetPucTagData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPucTagData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pucTagData, other.pucTagData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("KeyPairWithKek(");
    boolean first = true;

    sb.append("handler:");
    sb.append(this.handler);
    first = false;
    if (!first) sb.append(", ");
    sb.append("pubKey:");
    if (this.pubKey == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.pubKey, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("priKey:");
    if (this.priKey == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.priKey, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("pucTagData:");
    if (this.pucTagData == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.pucTagData, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class KeyPairWithKekStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public KeyPairWithKekStandardScheme getScheme() {
      return new KeyPairWithKekStandardScheme();
    }
  }

  private static class KeyPairWithKekStandardScheme extends org.apache.thrift.scheme.StandardScheme<KeyPairWithKek> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, KeyPairWithKek struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // HANDLER
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.handler = iprot.readI64();
              struct.setHandlerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PUB_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.pubKey = iprot.readBinary();
              struct.setPubKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PRI_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.priKey = iprot.readBinary();
              struct.setPriKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PUC_TAG_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.pucTagData = iprot.readBinary();
              struct.setPucTagDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, KeyPairWithKek struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(HANDLER_FIELD_DESC);
      oprot.writeI64(struct.handler);
      oprot.writeFieldEnd();
      if (struct.pubKey != null) {
        oprot.writeFieldBegin(PUB_KEY_FIELD_DESC);
        oprot.writeBinary(struct.pubKey);
        oprot.writeFieldEnd();
      }
      if (struct.priKey != null) {
        oprot.writeFieldBegin(PRI_KEY_FIELD_DESC);
        oprot.writeBinary(struct.priKey);
        oprot.writeFieldEnd();
      }
      if (struct.pucTagData != null) {
        oprot.writeFieldBegin(PUC_TAG_DATA_FIELD_DESC);
        oprot.writeBinary(struct.pucTagData);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class KeyPairWithKekTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public KeyPairWithKekTupleScheme getScheme() {
      return new KeyPairWithKekTupleScheme();
    }
  }

  private static class KeyPairWithKekTupleScheme extends org.apache.thrift.scheme.TupleScheme<KeyPairWithKek> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, KeyPairWithKek struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetHandler()) {
        optionals.set(0);
      }
      if (struct.isSetPubKey()) {
        optionals.set(1);
      }
      if (struct.isSetPriKey()) {
        optionals.set(2);
      }
      if (struct.isSetPucTagData()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetHandler()) {
        oprot.writeI64(struct.handler);
      }
      if (struct.isSetPubKey()) {
        oprot.writeBinary(struct.pubKey);
      }
      if (struct.isSetPriKey()) {
        oprot.writeBinary(struct.priKey);
      }
      if (struct.isSetPucTagData()) {
        oprot.writeBinary(struct.pucTagData);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, KeyPairWithKek struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.handler = iprot.readI64();
        struct.setHandlerIsSet(true);
      }
      if (incoming.get(1)) {
        struct.pubKey = iprot.readBinary();
        struct.setPubKeyIsSet(true);
      }
      if (incoming.get(2)) {
        struct.priKey = iprot.readBinary();
        struct.setPriKeyIsSet(true);
      }
      if (incoming.get(3)) {
        struct.pucTagData = iprot.readBinary();
        struct.setPucTagDataIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

