/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package kl.hsm.server.svc.base;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-01-24")
public enum RsaPadding implements org.apache.thrift.TEnum {
  NoPadding(0),
  PKCS1_5(1),
  OAEP_SHA1(2),
  OAEP_SHA256(3),
  PSS(6);

  private final int value;

  private RsaPadding(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static RsaPadding findByValue(int value) { 
    switch (value) {
      case 0:
        return NoPadding;
      case 1:
        return PKCS1_5;
      case 2:
        return OAEP_SHA1;
      case 3:
        return OAEP_SHA256;
      case 6:
        return PSS;
      default:
        return null;
    }
  }
}
