/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package kl.hsm.server.svc.base;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-01-24")
public enum Sm9UserPriKeyType implements org.apache.thrift.TEnum {
  ENCRYPT(1),
  SIGN(2),
  EXCHANGE(3);

  private final int value;

  private Sm9UserPriKeyType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Sm9UserPriKeyType findByValue(int value) { 
    switch (value) {
      case 1:
        return ENCRYPT;
      case 2:
        return SIGN;
      case 3:
        return EXCHANGE;
      default:
        return null;
    }
  }
}
