/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package kl.hsm.server.svc.p11;

/**
 * GCM加密模式机制参数
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-01-24")
public class GCMParameter implements org.apache.thrift.TBase<GCMParameter, GCMParameter._Fields>, java.io.Serializable, Cloneable, Comparable<GCMParameter> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GCMParameter");

  private static final org.apache.thrift.protocol.TField IV_FIELD_DESC = new org.apache.thrift.protocol.TField("iv", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField AAD_FIELD_DESC = new org.apache.thrift.protocol.TField("aad", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField TAG_BITS_FIELD_DESC = new org.apache.thrift.protocol.TField("tagBits", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField IV_BITS_FIELD_DESC = new org.apache.thrift.protocol.TField("ivBits", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new GCMParameterStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new GCMParameterTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer iv; // required
  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer aad; // required
  public int tagBits; // required
  public int ivBits; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IV((short)1, "iv"),
    AAD((short)2, "aad"),
    TAG_BITS((short)3, "tagBits"),
    IV_BITS((short)4, "ivBits");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IV
          return IV;
        case 2: // AAD
          return AAD;
        case 3: // TAG_BITS
          return TAG_BITS;
        case 4: // IV_BITS
          return IV_BITS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TAGBITS_ISSET_ID = 0;
  private static final int __IVBITS_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IV, new org.apache.thrift.meta_data.FieldMetaData("iv", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.AAD, new org.apache.thrift.meta_data.FieldMetaData("aad", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.TAG_BITS, new org.apache.thrift.meta_data.FieldMetaData("tagBits", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.IV_BITS, new org.apache.thrift.meta_data.FieldMetaData("ivBits", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GCMParameter.class, metaDataMap);
  }

  public GCMParameter() {
    this.tagBits = -1;

    this.ivBits = -1;

  }

  public GCMParameter(
    java.nio.ByteBuffer iv,
    java.nio.ByteBuffer aad,
    int tagBits,
    int ivBits)
  {
    this();
    this.iv = org.apache.thrift.TBaseHelper.copyBinary(iv);
    this.aad = org.apache.thrift.TBaseHelper.copyBinary(aad);
    this.tagBits = tagBits;
    setTagBitsIsSet(true);
    this.ivBits = ivBits;
    setIvBitsIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GCMParameter(GCMParameter other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetIv()) {
      this.iv = org.apache.thrift.TBaseHelper.copyBinary(other.iv);
    }
    if (other.isSetAad()) {
      this.aad = org.apache.thrift.TBaseHelper.copyBinary(other.aad);
    }
    this.tagBits = other.tagBits;
    this.ivBits = other.ivBits;
  }

  @Override
  public GCMParameter deepCopy() {
    return new GCMParameter(this);
  }

  @Override
  public void clear() {
    this.iv = null;
    this.aad = null;
    this.tagBits = -1;

    this.ivBits = -1;

  }

  public byte[] getIv() {
    setIv(org.apache.thrift.TBaseHelper.rightSize(iv));
    return iv == null ? null : iv.array();
  }

  public java.nio.ByteBuffer bufferForIv() {
    return org.apache.thrift.TBaseHelper.copyBinary(iv);
  }

  public GCMParameter setIv(byte[] iv) {
    this.iv = iv == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(iv.clone());
    return this;
  }

  public GCMParameter setIv(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer iv) {
    this.iv = org.apache.thrift.TBaseHelper.copyBinary(iv);
    return this;
  }

  public void unsetIv() {
    this.iv = null;
  }

  /** Returns true if field iv is set (has been assigned a value) and false otherwise */
  public boolean isSetIv() {
    return this.iv != null;
  }

  public void setIvIsSet(boolean value) {
    if (!value) {
      this.iv = null;
    }
  }

  public byte[] getAad() {
    setAad(org.apache.thrift.TBaseHelper.rightSize(aad));
    return aad == null ? null : aad.array();
  }

  public java.nio.ByteBuffer bufferForAad() {
    return org.apache.thrift.TBaseHelper.copyBinary(aad);
  }

  public GCMParameter setAad(byte[] aad) {
    this.aad = aad == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(aad.clone());
    return this;
  }

  public GCMParameter setAad(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer aad) {
    this.aad = org.apache.thrift.TBaseHelper.copyBinary(aad);
    return this;
  }

  public void unsetAad() {
    this.aad = null;
  }

  /** Returns true if field aad is set (has been assigned a value) and false otherwise */
  public boolean isSetAad() {
    return this.aad != null;
  }

  public void setAadIsSet(boolean value) {
    if (!value) {
      this.aad = null;
    }
  }

  public int getTagBits() {
    return this.tagBits;
  }

  public GCMParameter setTagBits(int tagBits) {
    this.tagBits = tagBits;
    setTagBitsIsSet(true);
    return this;
  }

  public void unsetTagBits() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TAGBITS_ISSET_ID);
  }

  /** Returns true if field tagBits is set (has been assigned a value) and false otherwise */
  public boolean isSetTagBits() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TAGBITS_ISSET_ID);
  }

  public void setTagBitsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TAGBITS_ISSET_ID, value);
  }

  public int getIvBits() {
    return this.ivBits;
  }

  public GCMParameter setIvBits(int ivBits) {
    this.ivBits = ivBits;
    setIvBitsIsSet(true);
    return this;
  }

  public void unsetIvBits() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __IVBITS_ISSET_ID);
  }

  /** Returns true if field ivBits is set (has been assigned a value) and false otherwise */
  public boolean isSetIvBits() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __IVBITS_ISSET_ID);
  }

  public void setIvBitsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __IVBITS_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case IV:
      if (value == null) {
        unsetIv();
      } else {
        if (value instanceof byte[]) {
          setIv((byte[])value);
        } else {
          setIv((java.nio.ByteBuffer)value);
        }
      }
      break;

    case AAD:
      if (value == null) {
        unsetAad();
      } else {
        if (value instanceof byte[]) {
          setAad((byte[])value);
        } else {
          setAad((java.nio.ByteBuffer)value);
        }
      }
      break;

    case TAG_BITS:
      if (value == null) {
        unsetTagBits();
      } else {
        setTagBits((java.lang.Integer)value);
      }
      break;

    case IV_BITS:
      if (value == null) {
        unsetIvBits();
      } else {
        setIvBits((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case IV:
      return getIv();

    case AAD:
      return getAad();

    case TAG_BITS:
      return getTagBits();

    case IV_BITS:
      return getIvBits();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case IV:
      return isSetIv();
    case AAD:
      return isSetAad();
    case TAG_BITS:
      return isSetTagBits();
    case IV_BITS:
      return isSetIvBits();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof GCMParameter)
      return this.equals((GCMParameter)that);
    return false;
  }

  public boolean equals(GCMParameter that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_iv = true && this.isSetIv();
    boolean that_present_iv = true && that.isSetIv();
    if (this_present_iv || that_present_iv) {
      if (!(this_present_iv && that_present_iv))
        return false;
      if (!this.iv.equals(that.iv))
        return false;
    }

    boolean this_present_aad = true && this.isSetAad();
    boolean that_present_aad = true && that.isSetAad();
    if (this_present_aad || that_present_aad) {
      if (!(this_present_aad && that_present_aad))
        return false;
      if (!this.aad.equals(that.aad))
        return false;
    }

    boolean this_present_tagBits = true;
    boolean that_present_tagBits = true;
    if (this_present_tagBits || that_present_tagBits) {
      if (!(this_present_tagBits && that_present_tagBits))
        return false;
      if (this.tagBits != that.tagBits)
        return false;
    }

    boolean this_present_ivBits = true;
    boolean that_present_ivBits = true;
    if (this_present_ivBits || that_present_ivBits) {
      if (!(this_present_ivBits && that_present_ivBits))
        return false;
      if (this.ivBits != that.ivBits)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetIv()) ? 131071 : 524287);
    if (isSetIv())
      hashCode = hashCode * 8191 + iv.hashCode();

    hashCode = hashCode * 8191 + ((isSetAad()) ? 131071 : 524287);
    if (isSetAad())
      hashCode = hashCode * 8191 + aad.hashCode();

    hashCode = hashCode * 8191 + tagBits;

    hashCode = hashCode * 8191 + ivBits;

    return hashCode;
  }

  @Override
  public int compareTo(GCMParameter other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetIv(), other.isSetIv());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIv()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.iv, other.iv);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAad(), other.isSetAad());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAad()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.aad, other.aad);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTagBits(), other.isSetTagBits());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTagBits()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tagBits, other.tagBits);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetIvBits(), other.isSetIvBits());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIvBits()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ivBits, other.ivBits);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("GCMParameter(");
    boolean first = true;

    sb.append("iv:");
    if (this.iv == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.iv, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("aad:");
    if (this.aad == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.aad, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("tagBits:");
    sb.append(this.tagBits);
    first = false;
    if (!first) sb.append(", ");
    sb.append("ivBits:");
    sb.append(this.ivBits);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GCMParameterStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public GCMParameterStandardScheme getScheme() {
      return new GCMParameterStandardScheme();
    }
  }

  private static class GCMParameterStandardScheme extends org.apache.thrift.scheme.StandardScheme<GCMParameter> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, GCMParameter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IV
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.iv = iprot.readBinary();
              struct.setIvIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // AAD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.aad = iprot.readBinary();
              struct.setAadIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TAG_BITS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.tagBits = iprot.readI32();
              struct.setTagBitsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // IV_BITS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.ivBits = iprot.readI32();
              struct.setIvBitsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, GCMParameter struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.iv != null) {
        oprot.writeFieldBegin(IV_FIELD_DESC);
        oprot.writeBinary(struct.iv);
        oprot.writeFieldEnd();
      }
      if (struct.aad != null) {
        oprot.writeFieldBegin(AAD_FIELD_DESC);
        oprot.writeBinary(struct.aad);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TAG_BITS_FIELD_DESC);
      oprot.writeI32(struct.tagBits);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(IV_BITS_FIELD_DESC);
      oprot.writeI32(struct.ivBits);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GCMParameterTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public GCMParameterTupleScheme getScheme() {
      return new GCMParameterTupleScheme();
    }
  }

  private static class GCMParameterTupleScheme extends org.apache.thrift.scheme.TupleScheme<GCMParameter> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GCMParameter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetIv()) {
        optionals.set(0);
      }
      if (struct.isSetAad()) {
        optionals.set(1);
      }
      if (struct.isSetTagBits()) {
        optionals.set(2);
      }
      if (struct.isSetIvBits()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetIv()) {
        oprot.writeBinary(struct.iv);
      }
      if (struct.isSetAad()) {
        oprot.writeBinary(struct.aad);
      }
      if (struct.isSetTagBits()) {
        oprot.writeI32(struct.tagBits);
      }
      if (struct.isSetIvBits()) {
        oprot.writeI32(struct.ivBits);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GCMParameter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.iv = iprot.readBinary();
        struct.setIvIsSet(true);
      }
      if (incoming.get(1)) {
        struct.aad = iprot.readBinary();
        struct.setAadIsSet(true);
      }
      if (incoming.get(2)) {
        struct.tagBits = iprot.readI32();
        struct.setTagBitsIsSet(true);
      }
      if (incoming.get(3)) {
        struct.ivBits = iprot.readI32();
        struct.setIvBitsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

