/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package kl.hsm.server.svc.p11;


/**
 * 对象类型
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-01-24")
public enum ObjectClass implements org.apache.thrift.TEnum {
  TCKO_DATA(0),
  TCKO_CERTIFICATE(1),
  TCKO_PUBLIC_KEY(2),
  TCKO_PRIVATE_KEY(3),
  TCKO_SECRET_KEY(4),
  TCKO_HW_FEATURE(5),
  TCKO_DOMAIN_PARAMETERS(6),
  TCKO_MECHANISM(7),
  TCKO_OTP_KEY(8),
  TCKO_VENDOR_DEFINED(-2147483648),
  TCKO_INVALID(-1);

  private final int value;

  private ObjectClass(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ObjectClass findByValue(int value) { 
    switch (value) {
      case 0:
        return TCKO_DATA;
      case 1:
        return TCKO_CERTIFICATE;
      case 2:
        return TCKO_PUBLIC_KEY;
      case 3:
        return TCKO_PRIVATE_KEY;
      case 4:
        return TCKO_SECRET_KEY;
      case 5:
        return TCKO_HW_FEATURE;
      case 6:
        return TCKO_DOMAIN_PARAMETERS;
      case 7:
        return TCKO_MECHANISM;
      case 8:
        return TCKO_OTP_KEY;
      case -2147483648:
        return TCKO_VENDOR_DEFINED;
      case -1:
        return TCKO_INVALID;
      default:
        return null;
    }
  }
}
