/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package kl.hsm.server.svc.p11;


/**
 * 返回值
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-01-24")
public enum Rv implements org.apache.thrift.TEnum {
  TCKR_OK(0),
  TCKR_CANCEL(1),
  TCKR_HOST_MEMORY(2),
  TCKR_SLOT_ID_INVALID(3),
  TCKR_GENERAL_ERROR(5),
  TCKR_FUNCTION_FAILED(6),
  TCKR_ARGUMENTS_BAD(7),
  TCKR_NO_EVENT(8),
  TCKR_NEED_TO_CREATE_THREADS(9),
  TCKR_CANT_LOCK(10),
  TCKR_ATTRIBUTE_READ_ONLY(16),
  TCKR_ATTRIBUTE_SENSITIVE(17),
  TCKR_ATTRIBUTE_TYPE_INVALID(18),
  TCKR_ATTRIBUTE_VALUE_INVALID(19),
  TCKR_ACTION_PROHIBITED(27),
  TCKR_DATA_INVALID(32),
  TCKR_DATA_LEN_RANGE(33),
  TCKR_DEVICE_ERROR(48),
  TCKR_DEVICE_MEMORY(49),
  TCKR_DEVICE_REMOVED(50),
  TCKR_ENCRYPTED_DATA_INVALID(64),
  TCKR_ENCRYPTED_DATA_LEN_RANGE(65),
  TCKR_FUNCTION_CANCELED(80),
  TCKR_FUNCTION_NOT_PARALLEL(81),
  TCKR_FUNCTION_NOT_SUPPORTED(84),
  TCKR_KEY_HANDLE_INVALID(96),
  TCKR_KEY_SIZE_RANGE(98),
  TCKR_KEY_TYPE_INCONSISTENT(99),
  TCKR_KEY_NOT_NEEDED(100),
  TCKR_KEY_CHANGED(101),
  TCKR_KEY_NEEDED(102),
  TCKR_KEY_INDIGESTIBLE(103),
  TCKR_KEY_FUNCTION_NOT_PERMITTED(104),
  TCKR_KEY_NOT_WRAPPABLE(105),
  TCKR_KEY_UNEXTRACTABLE(106),
  TCKR_MECHANISM_INVALID(112),
  TCKR_MECHANISM_PARAM_INVALID(113),
  TCKR_OBJECT_HANDLE_INVALID(130),
  TCKR_OPERATION_ACTIVE(144),
  TCKR_OPERATION_NOT_INITIALIZED(145),
  TCKR_PIN_INCORRECT(160),
  TCKR_PIN_INVALID(161),
  TCKR_PIN_LEN_RANGE(162),
  TCKR_PIN_EXPIRED(163),
  TCKR_PIN_LOCKED(164),
  TCKR_SESSION_CLOSED(176),
  TCKR_SESSION_COUNT(177),
  TCKR_SESSION_HANDLE_INVALID(179),
  TCKR_SESSION_PARALLEL_NOT_SUPPORTED(180),
  TCKR_SESSION_READ_ONLY(181),
  TCKR_SESSION_EXISTS(182),
  TCKR_SESSION_READ_ONLY_EXISTS(183),
  TCKR_SESSION_READ_WRITE_SO_EXISTS(184),
  TCKR_SIGNATURE_INVALID(192),
  TCKR_SIGNATURE_LEN_RANGE(193),
  TCKR_TEMPLATE_INCOMPLETE(208),
  TCKR_TEMPLATE_INCONSISTENT(209),
  TCKR_TOKEN_NOT_PRESENT(224),
  TCKR_TOKEN_NOT_RECOGNIZED(225),
  TCKR_TOKEN_WRITE_PROTECTED(226),
  TCKR_UNWRAPPING_KEY_HANDLE_INVALID(240),
  TCKR_UNWRAPPING_KEY_SIZE_RANGE(241),
  TCKR_UNWRAPPING_KEY_TYPE_INCONSISTENT(242),
  TCKR_USER_ALREADY_LOGGED_IN(256),
  TCKR_USER_NOT_LOGGED_IN(257),
  TCKR_USER_PIN_NOT_INITIALIZED(258),
  TCKR_USER_TYPE_INVALID(259),
  TCKR_USER_ANOTHER_ALREADY_LOGGED_IN(260),
  TCKR_USER_TOO_MANY_TYPES(261),
  TCKR_WRAPPED_KEY_INVALID(272),
  TCKR_WRAPPED_KEY_LEN_RANGE(274),
  TCKR_WRAPPING_KEY_HANDLE_INVALID(275),
  TCKR_WRAPPING_KEY_SIZE_RANGE(276),
  TCKR_WRAPPING_KEY_TYPE_INCONSISTENT(277),
  TCKR_RANDOM_SEED_NOT_SUPPORTED(288),
  TCKR_RANDOM_NO_RNG(289),
  TCKR_DOMAIN_PARAMS_INVALID(304),
  TCKR_CURVE_NOT_SUPPORTED(320),
  TCKR_BUFFER_TOO_SMALL(336),
  TCKR_SAVED_STATE_INVALID(352),
  TCKR_INFORMATION_SENSITIVE(368),
  TCKR_STATE_UNSAVEABLE(384),
  TCKR_CRYPTOKI_NOT_INITIALIZED(400),
  TCKR_CRYPTOKI_ALREADY_INITIALIZED(401),
  TCKR_MUTEX_BAD(416),
  TCKR_MUTEX_NOT_LOCKED(417),
  TCKR_NEW_PIN_MODE(432),
  TCKR_NEXT_OTP(433),
  TCKR_EXCEEDED_MAX_ITERATIONS(437),
  TCKR_FIPS_SELF_TEST_FAILED(438),
  TCKR_LIBRARY_LOAD_FAILED(439),
  TCKR_PIN_TOO_WEAK(440),
  TCKR_PUBLIC_KEY_INVALID(441),
  TCKR_FUNCTION_REJECTED(512),
  TCKR_VENDOR_DEFINED(-2147483648),
  TCKR_INVALID(-1);

  private final int value;

  private Rv(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Rv findByValue(int value) { 
    switch (value) {
      case 0:
        return TCKR_OK;
      case 1:
        return TCKR_CANCEL;
      case 2:
        return TCKR_HOST_MEMORY;
      case 3:
        return TCKR_SLOT_ID_INVALID;
      case 5:
        return TCKR_GENERAL_ERROR;
      case 6:
        return TCKR_FUNCTION_FAILED;
      case 7:
        return TCKR_ARGUMENTS_BAD;
      case 8:
        return TCKR_NO_EVENT;
      case 9:
        return TCKR_NEED_TO_CREATE_THREADS;
      case 10:
        return TCKR_CANT_LOCK;
      case 16:
        return TCKR_ATTRIBUTE_READ_ONLY;
      case 17:
        return TCKR_ATTRIBUTE_SENSITIVE;
      case 18:
        return TCKR_ATTRIBUTE_TYPE_INVALID;
      case 19:
        return TCKR_ATTRIBUTE_VALUE_INVALID;
      case 27:
        return TCKR_ACTION_PROHIBITED;
      case 32:
        return TCKR_DATA_INVALID;
      case 33:
        return TCKR_DATA_LEN_RANGE;
      case 48:
        return TCKR_DEVICE_ERROR;
      case 49:
        return TCKR_DEVICE_MEMORY;
      case 50:
        return TCKR_DEVICE_REMOVED;
      case 64:
        return TCKR_ENCRYPTED_DATA_INVALID;
      case 65:
        return TCKR_ENCRYPTED_DATA_LEN_RANGE;
      case 80:
        return TCKR_FUNCTION_CANCELED;
      case 81:
        return TCKR_FUNCTION_NOT_PARALLEL;
      case 84:
        return TCKR_FUNCTION_NOT_SUPPORTED;
      case 96:
        return TCKR_KEY_HANDLE_INVALID;
      case 98:
        return TCKR_KEY_SIZE_RANGE;
      case 99:
        return TCKR_KEY_TYPE_INCONSISTENT;
      case 100:
        return TCKR_KEY_NOT_NEEDED;
      case 101:
        return TCKR_KEY_CHANGED;
      case 102:
        return TCKR_KEY_NEEDED;
      case 103:
        return TCKR_KEY_INDIGESTIBLE;
      case 104:
        return TCKR_KEY_FUNCTION_NOT_PERMITTED;
      case 105:
        return TCKR_KEY_NOT_WRAPPABLE;
      case 106:
        return TCKR_KEY_UNEXTRACTABLE;
      case 112:
        return TCKR_MECHANISM_INVALID;
      case 113:
        return TCKR_MECHANISM_PARAM_INVALID;
      case 130:
        return TCKR_OBJECT_HANDLE_INVALID;
      case 144:
        return TCKR_OPERATION_ACTIVE;
      case 145:
        return TCKR_OPERATION_NOT_INITIALIZED;
      case 160:
        return TCKR_PIN_INCORRECT;
      case 161:
        return TCKR_PIN_INVALID;
      case 162:
        return TCKR_PIN_LEN_RANGE;
      case 163:
        return TCKR_PIN_EXPIRED;
      case 164:
        return TCKR_PIN_LOCKED;
      case 176:
        return TCKR_SESSION_CLOSED;
      case 177:
        return TCKR_SESSION_COUNT;
      case 179:
        return TCKR_SESSION_HANDLE_INVALID;
      case 180:
        return TCKR_SESSION_PARALLEL_NOT_SUPPORTED;
      case 181:
        return TCKR_SESSION_READ_ONLY;
      case 182:
        return TCKR_SESSION_EXISTS;
      case 183:
        return TCKR_SESSION_READ_ONLY_EXISTS;
      case 184:
        return TCKR_SESSION_READ_WRITE_SO_EXISTS;
      case 192:
        return TCKR_SIGNATURE_INVALID;
      case 193:
        return TCKR_SIGNATURE_LEN_RANGE;
      case 208:
        return TCKR_TEMPLATE_INCOMPLETE;
      case 209:
        return TCKR_TEMPLATE_INCONSISTENT;
      case 224:
        return TCKR_TOKEN_NOT_PRESENT;
      case 225:
        return TCKR_TOKEN_NOT_RECOGNIZED;
      case 226:
        return TCKR_TOKEN_WRITE_PROTECTED;
      case 240:
        return TCKR_UNWRAPPING_KEY_HANDLE_INVALID;
      case 241:
        return TCKR_UNWRAPPING_KEY_SIZE_RANGE;
      case 242:
        return TCKR_UNWRAPPING_KEY_TYPE_INCONSISTENT;
      case 256:
        return TCKR_USER_ALREADY_LOGGED_IN;
      case 257:
        return TCKR_USER_NOT_LOGGED_IN;
      case 258:
        return TCKR_USER_PIN_NOT_INITIALIZED;
      case 259:
        return TCKR_USER_TYPE_INVALID;
      case 260:
        return TCKR_USER_ANOTHER_ALREADY_LOGGED_IN;
      case 261:
        return TCKR_USER_TOO_MANY_TYPES;
      case 272:
        return TCKR_WRAPPED_KEY_INVALID;
      case 274:
        return TCKR_WRAPPED_KEY_LEN_RANGE;
      case 275:
        return TCKR_WRAPPING_KEY_HANDLE_INVALID;
      case 276:
        return TCKR_WRAPPING_KEY_SIZE_RANGE;
      case 277:
        return TCKR_WRAPPING_KEY_TYPE_INCONSISTENT;
      case 288:
        return TCKR_RANDOM_SEED_NOT_SUPPORTED;
      case 289:
        return TCKR_RANDOM_NO_RNG;
      case 304:
        return TCKR_DOMAIN_PARAMS_INVALID;
      case 320:
        return TCKR_CURVE_NOT_SUPPORTED;
      case 336:
        return TCKR_BUFFER_TOO_SMALL;
      case 352:
        return TCKR_SAVED_STATE_INVALID;
      case 368:
        return TCKR_INFORMATION_SENSITIVE;
      case 384:
        return TCKR_STATE_UNSAVEABLE;
      case 400:
        return TCKR_CRYPTOKI_NOT_INITIALIZED;
      case 401:
        return TCKR_CRYPTOKI_ALREADY_INITIALIZED;
      case 416:
        return TCKR_MUTEX_BAD;
      case 417:
        return TCKR_MUTEX_NOT_LOCKED;
      case 432:
        return TCKR_NEW_PIN_MODE;
      case 433:
        return TCKR_NEXT_OTP;
      case 437:
        return TCKR_EXCEEDED_MAX_ITERATIONS;
      case 438:
        return TCKR_FIPS_SELF_TEST_FAILED;
      case 439:
        return TCKR_LIBRARY_LOAD_FAILED;
      case 440:
        return TCKR_PIN_TOO_WEAK;
      case 441:
        return TCKR_PUBLIC_KEY_INVALID;
      case 512:
        return TCKR_FUNCTION_REJECTED;
      case -2147483648:
        return TCKR_VENDOR_DEFINED;
      case -1:
        return TCKR_INVALID;
      default:
        return null;
    }
  }
}
