/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package kl.hsm.server.svc.p11;


/**
 * 用户类型
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-01-24")
public enum UserType implements org.apache.thrift.TEnum {
  TCKU_SO(0),
  TCKU_USER(1),
  TCKU_CONTEXT_SPECIFIC(2),
  TCKU_INVALID(-1);

  private final int value;

  private UserType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static UserType findByValue(int value) { 
    switch (value) {
      case 0:
        return TCKU_SO;
      case 1:
        return TCKU_USER;
      case 2:
        return TCKU_CONTEXT_SPECIFIC;
      case -1:
        return TCKU_INVALID;
      default:
        return null;
    }
  }
}
